window.Lass=window.Lass||{version:0.1};
(function(a){var b=this.Util={};b.type=function(a){var c,b=/\{\s*\[native\s*code\]\s*\}/i;null===a?c="null":"undefined"===typeof a?c="undefined":(c=Object.prototype.toString.call(a).match(/\w+/g)[1].toLowerCase(),"object"===c&&b.test(a+"")&&(c="function"));return c};b.trim=function(a){return(a+"").replace(/^[\s\u00A0]+|[\s\u00A0]+$/g,"")};b.extend=function(){var f=arguments.callee,c,e;"object"!==b.type(arguments[0])?(c=1,e=!!arguments[0]):(c=0,e=!1);var d=arguments[c]||{};c=[].slice.call(arguments,
c+1);for(var h,j;c.length;)if(h=c.shift(),"object"===b.type(h)){var g,i;for(i in h)if(g=h[i],"object"===b.type(g))if(g==a||g==document||"childNodes"in g&&"nextSibling"in g&&"nodeType"in g){if(e||!(i in d))d[i]=g}else if(g.jquery&&/^[\d\.]+$/.test(g.jquery))d[i]=g;else{j=b.type(d[i]);if(!(i in d)||"undefined"===j||"null"===j)d[i]={};"object"===b.type(d[i])&&f(e,d[i],g)}else if(e||!(i in d))d[i]=g}return d};b.console=function(a){var c=!0,e=function(){},d={ON:!0,OFF:!1},e={SWITCH:d,turn:function(a){c=
d[a?"ON":"OFF"]},log:e,info:e,warn:e,error:e,debug:e};if(!a)return e;a.debug||(a.debug=a.log);a.error||(a.error=a.warn);return b.extend(!0,e,{log:function(b){c===d.ON&&a.log(b)},info:function(b){c===d.ON&&a.info(b)},warn:function(b){c===d.ON&&a.warn(b)},error:function(b){c===d.ON&&a.error(b)},debug:function(b){c===d.ON&&a.debug(b)}})}.call(a,a.console);return b}).call(Lass,window);
(function(){var a=this.String={};a.startWidth=function(a,f){return a.slice(0,f.length)===f};a.endWidth=function(){};a.isString=function(a){return"string"===typeof a}}).call(Lass);
(function(){var a=this.Array={};a.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)?!0:!1};a.indexOf=function(a,f,c){for(var e=-1,c=("number"===this.Util.type(c)?c:-1)+1,d=a.length;c<d;c++)if(a[c]===f){e=c;break}return e};a.unique=function(b){for(var f=[],c=0,e=b.length;c<e;c++)-1===a.indexOf(f,b[c])&&f.push(b[c]);return f}}).call(Lass);(function(){this.Hash={}}).call(Lass);(function(){(this.Element={}).isElement=function(a){return!a?!1:1===a.nodeType}}).call(Lass);
(function(a){var b=this.Timer={};b.requestAnimationFrame=a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||function(a){setTimeout(a,1E3/60)};b.isSupportRequestAnimationFrame=function(){return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame&&a.mozCancelRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame};b.RequestInterval=function(f,c){function e(){(new Date).getTime()-
d>=c&&(f.call(),d=(new Date).getTime());h.value=b.requestAnimationFrame.call(a,e)}if(!b.isSupportRequestAnimationFrame())return a.setInterval(f,c);var d=(new Date).getTime(),h={};h.value=b.requestAnimationFrame.call(a,e);return h};b.clearRequestInterval=function(b){a.cancelRequestAnimationFrame?a.cancelRequestAnimationFrame(b.value):a.webkitCancelAnimationFrame?a.webkitCancelAnimationFrame(b.value):a.webkitCancelRequestAnimationFrame?a.webkitCancelRequestAnimationFrame(b.value):a.mozCancelRequestAnimationFrame?
a.mozCancelRequestAnimationFrame(b.value):a.oCancelRequestAnimationFrame?a.oCancelRequestAnimationFrame(b.value):a.msCancelRequestAnimationFrame?a.msCancelRequestAnimationFrame(b.value):clearInterval(b)};b.RequestTimeout=function(f,c){function e(){(new Date).getTime()-d>=c?f.call():h.value=b.requestAnimationFrame.call(a,e)}if(!b.isSupportRequestAnimationFrame())return a.setTimeout(f,c);var d=(new Date).getTime(),h={};h.value=b.requestAnimationFrame.call(a,e);return h};b.clearRequestTimeout=function(b){a.cancelRequestAnimationFrame?
a.cancelRequestAnimationFrame(b.value):a.webkitCancelAnimationFrame?a.webkitCancelAnimationFrame(b.value):a.webkitCancelRequestAnimationFrame?a.webkitCancelRequestAnimationFrame(b.value):a.mozCancelRequestAnimationFrame?a.mozCancelRequestAnimationFrame(b.value):a.oCancelRequestAnimationFrame?a.oCancelRequestAnimationFrame(b.value):a.msCancelRequestAnimationFrame?a.msCancelRequestAnimationFrame(b.value):clearTimeout(b)}}).call(Lass,window);
